# 환경별 application.yaml 파일
spring:
  profiles:
    active: local
  # App 종료시
  lifecycle:
    timeout-per-shutdown-phase: 30s  #Graceful Shutdown시 쓰레드가 종료를 기다리는 시간 (default 30s)


    # App Port
    server:
      port: 8080
      shutdown: graceful  # Graceful Shutdown 활성화 - 쓰레드가 완전히 종료 될때까지 기다림
      #shutdown: immediate  # Graceful Shutdown 비활성화 - 쓰레드를 바로 중지 시키고 App을 종료함