apiVersion: v1
kind: Namespace
metadata:
  name: dev-tools
  labels:
    managed-by: kubectl




---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data
  namespace: dev-tools
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: dev-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - image: sonatype/nexus3:3.63.0
          name: nexus
          ports:
            - containerPort: 8081
              protocol: TCP
          volumeMounts:
            - mountPath: /nexus-data
              name: nexus-data
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-data
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: dev-tools
spec:
  ports:
    - name: nexus
      port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 30200
  selector:
    app: nexus
  type: NodePort